name: clang-format Code Formatter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Clang Code Formatter
      uses: egor-tensin/clang-format@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}